CREATE TABLE IF NOT EXISTS "Question" (
	"_id"	INTEGER NOT NULL UNIQUE,
	"position"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT NOT NULL,
	"text"	TEXT NOT NULL,
	"image"	TEXT,
	PRIMARY KEY("_id" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "Answer" (
	"_id"	INTEGER NOT NULL UNIQUE,
	"text"	TEXT NOT NULL,
	"isCorrect"	INTEGER NOT NULL,
    "question" INTEGER NOT NULL,
	PRIMARY KEY("_id" AUTOINCREMENT),
    FOREIGN KEY("question") REFERENCES "Question"("_id")
);